services:
  otelcol:
    image: "otel/opentelemetry-collector"
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    volumes:
      - ./config.yaml:/etc/otelcol/config.yaml 
    command: 
      - '--config=/etc/otelcol/config.yaml'
    depends_on:
      - prometheus
      - grafana

